### ISSUE TITLE
Release 0.5.9 version of origin.js

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-js#104]
## Confirm readiness
- [x] _origin-js_: Confirm js tests passing
  - `npm checkout develop`
  - `npm pull`
  - `npm run install:dev`
  - `npm test` (This will also test smart contracts)
  - `npm start`
- [x] _demo-dapp_: Confirm all tests passing
- [x] _demo-dapp_: Confirm it runs against remote origin-js
  - `npm checkout develop`
  - `npm pull`
  - `npm run install`
  - `npm start`
- [x] _demo-dapp_: Confirm it runs against local origin-js
  - `npm checkout develop`
  - `npm pull`
  - `npm run install:dev`
  - `npm start`
- [x] _demo-dapp_: Replace git reference with version number in `package.json`
  -   ` "origin": "OriginProtocol/origin-js#develop"` --> `"origin": "0.5.9"`
- [x] Confirm deployment accounts have eth for gas
  - [x] Rinkeby ([Faucet](https://faucet.rinkeby.io/)) 
    - Public post for [0]: `https://plus.google.com/u/0/114203467826302852415/posts/F7sJZMGCbgg`
    - [x] account[0] `0x1a5c29c94d03c4c8f7414564cbd57295d61e898f`
    - [x] account[1] `0x564aae0251d49d1f8d4d8d9e5da08f8cceff9ef2`
  - [x] Ropsten ([Faucet](https://faucet.metamask.io/))
    - [x] account[0] `0x1a5c29c94d03c4c8f7414564cbd57295d61e898f`
    - [x] account[1] `0x564aae0251d49d1f8d4d8d9e5da08f8cceff9ef2`

## Publish
- [x] If contracts have changed:
  - Show diff with: `git diff master..develop contracts/contracts/`
  - `cd contracts`
  - [x] Deploy new smart contracts to Ropsten. Be sure addresses are listed in ABI files. 
    - `export ROPSTEN_MNEMONIC="<mnemonic>"`
    - `npx truffle migrate --network ropsten`
  - [x] Deploy new smart contracts to Rinkeby.  Be sure addresses are listed in ABI files. 
    - `export RINKEBY_MNEMONIC="<mnemonic>"`
    - `npx truffle migrate --network rinkeby`
  - [x] Migrate data from old contracts to new. (Once we get around to writing migrations!)
- [x] _origin-js_: Build origin.js (in `dist/origin.js`)
    - `npm run install:dev`
- [x] _demo-dapp_: Merge `develop` into `master` and push
- [x] _origin-js_: Merge `develop` into `master` and push
- [x] _origin-js_: Create new [GitHub release](https://github.com/OriginProtocol/origin-js/releases) with origin.js code,
  - [x] Version in form `v0.5.9` (This will add git tag on `master`)
  - [x] Include addresses of smart contracts in description
- [x] _demo-dapp_: Add git tag to `master` to match origin-js and push.
  - `git tag -a v0.5.9 -m "New release"`
- [x] _origin-js_: [Publish to npm](https://docs.npmjs.com/cli/publish). 
  - `npm publish`
- [ ] _demo-dapp_: Deploy new version of dapp to heroku (url to be determined)

## Follow-up
- [x] Confirm published `origin.js` file is accessible via `code.originprotocol.com` redirect
  - https://unpkg.com/origin@0.5.9/dist/origin.js for now
- [ ] _demo-dapp_: Confirm that "one-line setup & run" command works on `master` branch shown by default
- [ ] _demo-dapp_: confirm its using npm package works and can find contracts
- [ ] _origin-js_: Increment version number to  on `develop` to for next release
- [ ] _demo-dapp_: Replace version number with git reference in `package.json`
  -`"origin": "0.5.9"` --> ` "origin": "OriginProtocol/origin-js#develop"`
- [ ] _docs_: Review docs for needed updates. Confirm example code on playground site (jsfiddle?) still work.
- [ ] Copy this to-do list into new issue for next sprint.
- [ ] Post notice of new release on Discord

**Comment by joshfraser** [comment]
We now have `origin` on npm. Will need to bump our version numbers to avoid conflicts with the previous library.

What do we do with the old handle? Can we setup a redirect or something?

**Comment by DanielVF** [comment]
At least one option is to "deprecate" the old one.

https://docs.npmjs.com/cli/deprecate

**Comment by wanderingstan** [comment]
@joshfraser @DanielVF handled npm rename in release for latest sprint:
https://github.com/OriginProtocol/origin-js/issues/101

**Comment by wanderingstan** [comment]
Rinkeby success:
```
~/Origin/origin-js/contracts$ npx truffle migrate --reset --network rinkeby
Using network 'rinkeby'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0x7a22497a6f2f51a62fdec67823634cb474c92f56a00cc5f0cb1e56384cd86504
  Migrations: 0xac824c89eab1b2e1b92f0e1675b49d5ddaee06fe
Saving successful migration to network...
  ... 0xe48d47caa8f2944d97cdfeed7fbfb8c7cc9a4aff90b712c041699d28b4065e47
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Running step...
  Replacing PurchaseLibrary...
  ... 0xd07f3b247d8cd8462d0f540ade54059911430178d6407aecfd6eecb4f55926c9
  PurchaseLibrary: 0xf3d23900cd3cf2401cfb78f4143157c5db0b18f0
  Linking PurchaseLibrary to ListingsRegistry
  Linking PurchaseLibrary to Listing
  Replacing ListingsRegistry...
  ... 0x37a5ac2e4c17a34296724a9f8c3a62b935dd7ee9586ec112aac07c7e3037e079
  ListingsRegistry: 0xadb38358b69b28af99228e64c0b5c572053bc41c
  Replacing UserRegistry...
  ... 0x5c3b143c9a1cb4585d87d1e932396550a9aa3aba20c02e8c05df8c8e727257f0
  UserRegistry: 0x824e18a77e72a707986278471de0e90524019250
  Deploying OriginIdentity...
  ... 0xf42d29cffb181b8a25fffdfe0d873449d8dde0a5d66a924b3d2b14be9c102333
  OriginIdentity: 0xfee0ae42738f8391494eb307e8902052181a998d
Saving successful migration to network...
  ... 0xe515e5ee2aff8d9fc8bc8ee730c4efbfa8b8341985459c6ab07dab3040ed6fcc
Saving artifacts...
Running migration: 3_create_sample_listings.js
  Running step...
default_account: 0x1a5c29c94d03c4c8f7414564cbd57295d61e898f
a_seller_account: 0x564aae0251d49d1f8d4d8d9e5da08f8cceff9ef2
a_buyer_account: 0x47d4e5afd1624ea63cd7ace59d5dc1d87cff3bb5
another_buyer_account: 0xb7cc090637f6af85e3ed8cc623a5efe95b90b9f9
  ... 0x8e2e06873eb8640500a9c944a771dc9a5a7d7303361ba7194c795f5619142679
  ... 0xa58ad1102e86a5712b2281c864fec9efcbde39d94ecbf59eba0369d9d79daa04
  ... 0x23d9bcbe552cad063e20aadb27eed205d4ebf8b1f744faed081b4169b2834ade
  ... 0xb280d4952b5a7138b46e1216c79a7dd60c986f562e0734a725b98e956bcfe4bc
  ... 0xfd628f3dfe2f05d658aa0821627b65095fc47988f737c9fba647e737301a037f
Saving successful migration to network...
  ... 0x64cbaf29520d4a8f9b9d45c17ffe35fdee371046374ac84f91e13e9a5a0ec277
Saving artifacts...
Running migration: 4_add_sample_issuers.js
  Running step...
  ... 0xffa370e1209737d8612a83513bd3286f214bc4fc4c9dcd0a1a225274668ea46d
  ... 0xdbdb3efcbc2de5a3543d198a71d2836e1ca93b1c31aa149a3c3fb36afb86d546
Saving successful migration to network...
  ... 0x58d4139cd0340017739ad85a7ee6f0b8bf8b526c3b8f9279be8f0f9237ab84cd
Saving artifacts...
```

**Comment by wanderingstan** [comment]
**Ropsten** migration
```
Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0x62bf146980aff680688344a822936f32f95d993206f6aadf6c1440eac15274a3
  Migrations: 0x602c580069303001f17c4090e70b5ad2efd9da72
Saving successful migration to network...
  ... 0xcdc0ab8c1b9e4fd0e6542bd0bf588547fc2b3642622b63fa7ccb8b4424d49f72
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Running step...
  Replacing PurchaseLibrary...
  ... 0xec418ab366b67da831e209825e08c2cf3c0632167dbe998a2a8632ae9752cb00
  PurchaseLibrary: 0x2215fa58a5edc3679c89600b3b35d46cb1a82257
  Linking PurchaseLibrary to ListingsRegistry
  Linking PurchaseLibrary to Listing
  Replacing ListingsRegistry...
  ... 0x9bfa0c676a0918ba8298a804212e5c855e6764e6f3618648bb67a3c3d6ded1fc
  ListingsRegistry: 0x9adfb0b4a57b563329148096eead857b5564c062
  Replacing UserRegistry...
  ... 0x7674a266e286fa437151b5f75c8413e7afc34a07b2331023d432932cb9802fc8
  UserRegistry: 0x2b002d6ae372ba066aae7131a7fee7884b21a5ea
  Replacing OriginIdentity...
  ... 0x8e5f5257956e3dbe618a17ad936bf533ebbf3e6c76ef9cda6a5be0cf220b2e94
  OriginIdentity: 0x2c200990b6217504159f884673ee774f2fce9717
Saving successful migration to network...
  ... 0x640501362a35379063725eb396c555497a1e94840d305a2711ad292bf6f46907
Saving artifacts...
Running migration: 3_create_sample_listings.js
  Running step...
default_account: 0x1a5c29c94d03c4c8f7414564cbd57295d61e898f
a_seller_account: 0x564aae0251d49d1f8d4d8d9e5da08f8cceff9ef2
a_buyer_account: 0x47d4e5afd1624ea63cd7ace59d5dc1d87cff3bb5
another_buyer_account: 0xb7cc090637f6af85e3ed8cc623a5efe95b90b9f9
  ... 0x7d89ebbda8b5835a795e7235637aa04e8cf4973a397f0398078c2fc49a737ec0
  ... 0x5c9ad2547db51fd9e996444b2c91f8c2787ac970ccb51ba651e0f8118e2be8c5
  ... 0xa6d22789957249134d8807778fa507b9fb224bef4dac7da93f73c321b2145bde
  ... 0x6acc93d03cf7827ffe7bddffb6dd34349c32fc6dbcc88300d142ed993d3a3e74
  ... 0xec691e53322743d9af278ee46ed48c9ba7e5e08a38e7bfc5353cfc4b22aba840
Saving successful migration to network...
  ... 0x62f445246b07a939d3569891a06badc7a09050831211aa76bbb5cdaf044be860
Saving artifacts...
Running migration: 4_add_sample_issuers.js
  Running step...
  ... 0xac7a382b7aae7a0024136e4a888e02a88fccf9452c01381d35855d4a81ac4d50
  ... 0xf71f6a1a9c859a8725404576a92837e40d7329f69a355e6535ebcf7ae183f60b
Saving successful migration to network...
  ... 0x56de403eaf20a3d43574896699b84463a199833cb20d567a3f82d262d61cea33
Saving artifacts...
```

NOTE: Got this error over and over after migration was finished. What's up with that? 
```
JSON RPC response: ""
    at Object.InvalidResponse (/Users/stan/Origin/origin-js/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/stan/Origin/origin-js/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:414:24)
    at ClientRequest.emit (events.js:127:13)
    at TLSSocket.socketErrorListener (_http_client.js:394:9)
    at TLSSocket.emit (events.js:127:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/stan/Origin/origin-js/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/stan/Origin/origin-js/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/Users/stan/Origin/origin-js/node_modules/xhr2/lib/xhr2.js:414:24)
    at ClientRequest.emit (events.js:127:13)
    at TLSSocket.socketErrorListener (_http_client.js:394:9)
    at TLSSocket.emit (events.js:127:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by micahalcorn** [comment]
@wanderingstan https://github.com/OriginProtocol/origin-js/issues/143 cc @DanielVF

**Comment by wanderingstan** [comment]
Aborting this release since so much was still broken. `0.5.10` is out!
