### ISSUE TITLE
Ungraceful failure when web3 is not present

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#110]
This package [assumes that `web3` is available](https://github.com/OriginProtocol/origin-js/blob/61ce31e18069eb24af14969788e60bbe998b5920/src/contract-service.js#L21). Since there is no check, an exception of `Uncaught TypeError: Cannot read property 'currentProvider' of undefined` is thrown if it is not present.

In the DApp, we check for the presence of `web3` as a part of the rendering process but not before this package is imported.

**Is it the DApp's sole responsibility to provide `web3` prior to engaging with `origin-js` and/or should the package not assume that a global variable is present on the `window`?** I don't know whether or not it would appropriate for a package to yield anything other than a functional module or an exception.

cc @DanielVF @tyleryasaka

**Comment by ambertch** [comment]
If it's the former, one option might be using this render callback (https://medium.com/@adamrackis/simplifying-life-with-react-render-callbacks-cb37d58e55) with where origin-js is loaded (https://github.com/OriginProtocol/demo-dapp/blob/master/src/components/app.js#L75)

**Comment by ambertch** [comment]
With the latter, I think it's not unreasonable to have dependencies that are not immediately available during module import (a DB connection, for example).

I did a bit of research and saw an example of a dependency being injected into a component via triggering a re-render (by setting this.state).

**Comment by DanielVF** [comment]
@micahalcorn 

Snipping some lines here:
```
constructor({ web3 } = {}) {
     this.web3 = web3 || window.web3
```
..snip..
```
     this[name].setProvider(this.web3.currentProvider)
```

So origin.js will first use a web3 that you pass into it, but if you don't pass in a web3, then it will check the window for one and use that. This seems pretty good to me, though we should probably show some kind of error in the console if neither are true.

A DAPP should be responsible for making sure there is a web3, and for showing a whatever UI error we need to show if there isn't a web3 available.

**Comment by micahalcorn** [comment]
@nick we discussed this a little on Friday. I suppose that this might get resolved on the DApp side once we are supplying a version of `web3` (as opposed to relying on MetaMask's). As for the `origin-js` side, I think @tyleryasaka was going to take a look at this after knocking out some higher-priority issues.

**Comment by tyleryasaka** [comment]
> Is it the DApp's sole responsibility to provide web3 prior to engaging with origin-js and/or should the package not assume that a global variable is present on the window?

@micahalcorn I see what's going on now. The constructor for origin-js is called before web3 has been instantiated in the browser window. We assign `this.web3` in the constructor and use that reference from there on out. Thus web3 never gets properly defined. In fact, it crashes right there in the constructor because we try to call `this.web3.currentProvider`.

To answer your question: Yes I do think it is the dapp's responsibility to make sure web3 is present. I'll elaborate below.

1. origin-js does need to look for web3 at instantiation time. I think for origin-js to be able to function reliably it needs to have web3 present from the very beginning.

2. That said, origin-js should throw a much better error message if web3 is not present at instantiation time. I will create a PR to do this.

3. The solution in the dapp is to wait for web3 and *then* instantiate origin-js. I will also create a PR to do this in the demo-dapp.

**Comment by micahalcorn** [comment]
@tyleryasaka that makes sense, thanks. We were following the lead of [`react-web3`](https://www.npmjs.com/package/react-web3) to detect `web3` as a part of the rendering process. I believe that Nick's larger overhaul changes this, but it doesn't look like it does yet in [`redux-2`](https://github.com/originprotocol/demo-dapp/tree/redux-2).

**Comment by tyleryasaka** [comment]
I've got the first half of the fix in a PR: https://github.com/OriginProtocol/origin-js/pull/128

However, we can't merge that until the other half is done (updating demo dapp to pass in web3). I'm thinking the best way to go about that is to instantiate origin only after web3 has been loaded, and when that happens to place the origin instance in the redux store. Then the rest of the app can just access the instance from the store.

Any thoughts on that approach @nick ? Is this something you or @micahalcorn can take care of? I think I'm going to stay focused on ERC725/origin-js integration for now.

**Comment by micahalcorn** [comment]
Thanks, @tyleryasaka. I went ahead and created [an issue for us in demo-dapp](https://github.com/OriginProtocol/demo-dapp/issues/128). My only concern is that novice developers who add origin-js with a `script` tag won't know or be able to pass `web3` into the module.

Cc @wanderingstan

_This should not be prioritized over the goals of the current sprint._

**Comment by tyleryasaka** [comment]
@micahalcorn Yeah that's a valid concern. I'm not entirely opposed to having origin-js implicitly use `window.web3`. However, I think good documentation + a useful error message goes a long way towards reducing friction.

**Comment by micahalcorn** [comment]
@tyleryasaka I talked with @wanderingstan and he is good with your solution. Let's avoid the `window` for now. We'll will make sure that the DApp catches up in the next sprint.
