### ISSUE TITLE
Listing should be queried using ETH addresses

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#112]
Listings are currently referenced by their index ids because (according to @wanderingstan) there was originally a single contract and individual listings did not have their own ETH address. Can we go ahead and change [these](https://github.com/OriginProtocol/origin-js/blob/master/src/contract-service.js#L80) [methods](https://github.com/OriginProtocol/origin-js/blob/master/src/contract-service.js#L105) (and potentially others) to utilize the address rather than an index position? Or do we need to wait for the indexing service to be available? Or is there another reason not to use the address as a key?

cc @DanielVF

**Comment by DanielVF** [comment]
We definitely need to switch over to using the listing address as the main key for listings in the DAPP. I'll work on this.

**Comment by micahalcorn** [comment]
Resolved in #113 ✅
