### ISSUE TITLE
Update web3 to 1.0.x

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#124]
We need to confirm that [the upcoming version of web3](https://web3js.readthedocs.io/en/1.0/) will work with truffle. If so, swap out the current version. If not, come up with a plan B for integrating the identity front-end code.

**Comment by tyleryasaka** [comment]
Assigning myself because I'm going to tackle integrating ERC725 stuff with origin-js this week. I would say until Truffle supports web3 1.0 we just need to make ERC725 work with web3 0.x. I'm going to start down that route, and I'll report back if I run into any issues.
