### ISSUE TITLE
Return additional fields from IPFS

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/origin-js#139]
Origin.listings#get currently returns name, category, description, location, and pictures from IPFS. Additional fields would have to be returned in order to implement https://github.com/OriginProtocol/demo-dapp/issues/38. The field type may be good to return as well (for rendering).

Currently, the only additional field in the schemas is the datetime field of tickets.json

**Comment by wanderingstan** [comment]
Good point. This opens bigger questions I think. 

- From a security perspective, do we want to lock down which fields get returned? 
  - Some sort of whitelist of fields, perhaps from schema.org?
- Right now we're essentially hard-coding origin.js for the craigslist/ebay style listing. We should at least be thinking of a gameplan for other types of listings. 

@DanielVF , seems like something you'd have thoughts on.

**Comment by ambertch** [comment]
If additional fields are returned by Listings#get, the docs should also be updated to reflect that the API call can retrurn different fields depending on which type of listing it is, which fields will always get returned, etc.

**Comment by jordajm** [comment]
@wanderingstan @franckc @micahalcorn  - Coming across this ticket just now made me realize that the new implementation of the models in origin-js had a side-effect that I hadn't thought about before. 

That is, previously we were allowing a hypothetical dapp developer to extend the dapp listing schemas with any data they want and as long as it validates successfully against the origin-js listing schema, we'd store the data in IPFS and return it for them along with the other listing data.

However, the model now explicitly assigns values in the listing model, so if a dapp developer wanted to add additional fields to their dapp schemas, those fields would not be returned by the `getListing()` request. 

So, if a dapp developer wanted to add a field for "number of bedrooms" to the "for rent housing" schema in the dapp, we'd store that in IPFS but we wouldn't return it in the `getListing()` response. 

I'm thinking that we should take another look at the model implementations in origin-js and consider returning all data for listings somehow - maybe not at the top level of the `listing` object, but in a nested object called `data` or something?

For reference, the listing model is here:
https://github.com/OriginProtocol/origin/blob/master/origin-js/src/models/listing.js

**Comment by franckc** [comment]
@jordajm Those DApp custom fields will be returned in listing.ipfs.data. 
For example let's say a DApp schema has numBedrooms, it can be accessed by the DApp as listing.ipfs.data.numBedroom.
Do you think it is not enough ?

**Comment by franckc** [comment]
I'm going to close this issue since I think it is no longer relevant. Everyone feel free to re-open if you have reason to think otherwise.
