### ISSUE TITLE
Internal JSON-RPC error with some sample transactions

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#143]
On a seemingly random basis, one or more of the sample transactions generated [here](https://github.com/OriginProtocol/origin-js/blob/develop/contracts/migrations/3_create_sample_listings.js#L82-L91) result in `Error: Invalid JSON RPC response: {"id":19,"jsonrpc":"2.0","error":{"code":-32603}}` when running [`web3.eth.getBlock`](https://github.com/OriginProtocol/origin-js/blob/develop/src/resources/purchases.js#L81). Recompiling the contracts and generating new sample transactions often causes the error to occur with transactions related to different sample purchases.

**Comment by DanielVF** [comment]
Micah, if these steps work for you to clear the issue locally, I think that's as good as we can do for now.

This should not be an issue on the real blockchain, since it won't be restarting over it's block counts, and metamask won't have incorrectly cached data then.

**Comment by micahalcorn** [comment]
@DanielVF somehow I no longer get the JSON-RPC errors, I just get empty objects. Either way, the reset seems to work. Let's consider it solved and I'll document the fix in the readme.
