### ISSUE TITLE
Create first rev of Origin Token

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-js#144]
- Determine where in repo to put token code
- Choose base starting token code

Basically create a bare-bones ERC20 token.

**Comment by gaboesquivel** [comment]
You may want to take a look at https://github.com/knowledge/knowledge-contracts.
It's an upgradable ERC-20 token that follow current best practices for contracts development

**Comment by wanderingstan** [comment]
Going to call this done, as the token discussion has moved way beyond this point.
