### ISSUE TITLE
Remove ethereumjs-util dependency

### ISSUE THREAD

**Issue by tyleryasaka** [OriginProtocol/origin-js#153]
We're using `ethereumjs-util` to do signature validation. We should be able to do all this in web3 and remove this dependency.

**Comment by nick** [comment]
Although this is [possible](http://web3js.readthedocs.io/en/1.0/web3-eth-personal.html#ecrecover) with web3, it does not happen in the client and instead goes back to the node and, unfortunately, the personal_ecRecover method isn't supported everywhere (including Infura which is used by MetaMask).

Agree it'd be nice to remove the ethereumjs-util dependency though.

**Comment by tyleryasaka** [comment]
Ok, probably not worth it right now then. Closing.
