### ISSUE TITLE
Cannot deploy test listings to Ropsten/Rinkeby

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-js#156]
When deploying to testnets, `3_create_sample_listings.js` fails with `Error: invalid address`. 

Investigation showed that problem was accounts beyond the first one were empty strings. In these lines:
https://github.com/OriginProtocol/origin-js/blob/develop/contracts/migrations/3_create_sample_listings.js#L21-L24

Problem is our `HDWalletProvider` in this line:
https://github.com/OriginProtocol/origin-js/blob/develop/contracts/truffle.js#L24-L27

Turns out it only manages one account. This appears to be a known limit [described here](https://github.com/trufflesuite/truffle-hdwallet-provider). 

> Currently, the HDWalletProvider manages only one address at a time, but it can be easily upgraded to manage (i.e., "unlock") multiple addresses.

I couldn't find how to unlock multiple addresses as they described, in short time I had this morning. Help appreciated.

**Comment by micahalcorn** [comment]
@wanderingstan it looks like that README just hasn't been updated to document the `num_addresses` param allowed [here](https://github.com/trufflesuite/truffle-hdwallet-provider/commit/f930cc84550f8c10cffb81d44fde65fe4defce03#diff-168726dbe96b3ce427e7fedce31bb0bcR10). You should already have the correct version of the package (`0.0.5`) that includes the necessary commit.

**Comment by wanderingstan** [comment]
@micahalcorn found the fix here: https://github.com/OriginProtocol/origin-js/commit/dde3dfd869516756157c29b2280c1b66d11d5bfb
