### ISSUE TITLE
General information regarding the platform

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/origin-js#158]
Currently, general information pertaining to Origin, as well as information on other repos, resides in this repository's readme. I noticed that Orbit (https://github.com/orbitdb/orbit) has a "home page" repo where they link to the individual repos.

In the future, a repo that serves as a landing page of sorts could be helpful for developers new to the platform (linking to docs, bridge server, demo dapp, SDKs, etc)

**Comment by micahalcorn** [comment]
I think that the current intent is to consolidate the READMEs by pointing to the docs and/or a [developer landing page](https://github.com/OriginProtocol/company-website/issues/157).
