### ISSUE TITLE
🎓What is a trusted listing contract?

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-js#159]
We need to decide on how we decided that Listing contracts are trusted for use in the Origin. An important part of this discussion is if there is a single source of truth for this, or can different DApps support a different set of Listing contracts?

### Why do we need to know what is a trusted contract

Anyone can create a contract that matches the interface of an Origin Listing contract, and can emit events that cause it to be picked up by Origin bridge servers. However, a contract that exactly matches the external interface, can still contain evil logic inside. For example, an otherwise normal looking listing contract could immediately allow the buyers money to be withdrawn and then close the listing, preventing disputes.

Similarly, any contract in the world could call a record transaction on a user review registry contract to record a review, even if it was just a custom contract that spammed out a five hundred five star reviews. A review registry has to be able to know if the contract calling it is trusted.

To avoid this, DApps, contracts, and the bridge server have to have a way to whitelist trusted listing contracts. This way when they see an event come in, or go to a listing, they can verify that the code behind that contract is trusted.

### Centralized or per DApp trust?

One possible approach is that only Origin gets to pick trusted contracts. Every DApp uses the same centralized contract to validate contracts. 

- Easy to ensure that all contracts use Origin token or lose the benefits of the data ecosystem.
- One central place that knows about all possible Origin contracts
- We probably have to write much bigger, configurable contracts.
- Probably encourages forking everything 

The alternative approach is to have each DApp maintain its own whitelist of trusted contracts bytecodes.

- Easier to allow innovation and very different DApps
- Doesn't provide a single point to remove all contracts of a given type from operation

### Implementation Options

This trusted list can be done with either a registry of trusted contract addresses or with a list of trusted contract bytecodes.

Thoughts, @joshfraser?

----

Immediately effects:

- https://github.com/OriginProtocol/origin-js/issues/149
- https://github.com/OriginProtocol/bridge-server/issues/44

**Comment by joshfraser** [comment]
Thanks for opening this issue and putting this up for discussion. I don't know the right answer as there are pros and cons to both approaches as you laid out.

One thing I'll add is the possibility of us using a staking mechanism as a way of ensuring good behavior. For example, we could keep a very simple registry which keeps track of all of the listings on the Origin network, whether they're using our exact bytecode or not. The important thing is that you have to submit a large deposit that will be forfeited if you are proven to be a bad actor in some way. 

Obviously there is a lot of complexity that I'm brushing over on how that would work, but at a high level crypto-economic incentives could give us the safety we need without compromising on the innovation/flexibility of the other approach.

**Comment by tyleryasaka** [comment]
So here is my thinking. [We already have a listing registry in place](https://github.com/OriginProtocol/origin-js/blob/master/contracts/contracts/ListingsRegistry.sol). Currently it has [an array which stores all listings](https://github.com/OriginProtocol/origin-js/blob/master/contracts/contracts/ListingsRegistry.sol#L25). (We may need to convert that to a mapping but that's a technical detail.) We should just be able to say that all listings in the listing registry are valid, and all listings not in the registry are not valid. Then the ListingsRegistry contract can act as the gatekeeper and provide a method which creates a listing (using the correct listing contract) and adds it to the array/mapping of trusted listings. The dapp can either directly validate listing contracts by looking them up on the ListingRegistry contract, or the bridge server can do this validation and the dapp can just trust the bridge server.

Our listing registry [is actually already doing all of this](https://github.com/OriginProtocol/origin-js/blob/master/contracts/contracts/ListingsRegistry.sol#L91). So I'm a bit confused as to what the difficulty is here. Not seeing the need to examine any bytecode or introduce staking for this particular problem. Am I missing something?

If we're concerned about more complex scenarios, this same approach can be made more flexible, either now or in subsequent iterations.
- We can support multiple valid listing contracts by providing multiple `create` functions on the ListingsRegistry contract, one for each type of listing contract that is supported.
- We can have a global origin-level listing registry, or we can let each dapp/marketplace have its own registry. That's a separate discussion, but my point is that this method of validation works either way.
- We can integrate token economics with the listings registry if we want to. This might be a natural fit, as we may want to treat spots on the registry as a scarce resource, almost like real estate. This would discourage spamming. For example, creating a listing might require a deposit of 1 token, which would be returned to the creator of the listing once the listing is purchased/closed. Then demand of the marketplace would determine the cost of a token and provide an incentive for people to relinquish listing "spots" they are not using. Just a thought; token economics are complicated. Point being, there's a lot we could do here.

Thoughts? Am I thinking about this the right way?

Side tangent on the token thing: Could do a more flexible token integration where you could submit any number of tokens with your listing, and the dapps would just use some system to either prioritize listings by number of tokens attached or be able to set an arbitrary threshold for listings to show up in the dapp - and the threshold could be adjusted over time to accommodate changing needs of the marketplace. This would make the system resilient to changes in demand over time without having to change the actual supply of tokens (which we don't want any central authority to have the power to do for obvious reasons). Total side tangent, I know. Just don't want to lose this train of thought. 😃

**Comment by DanielVF** [comment]
If we are going with the single Origin owned Listing API registry for this release, I think we should go ahead and change the registry code so that we can have a constant time lookup to see if a contract addresses is a valid address.

Secondly, we might want to allow changing which PurchaseLibrary contract is used to create new contracts. This way for the near term we can keep the same ListingRegistry during release, but change it to create newer contracts.

**Comment by nick** [comment]
I like this approach, though perhaps we could call the LRR something like 'TrustedRegistries' or simply 'Registries'. I can see the Registries contract holding other information about ListingRegistries too, such as a 'type' (eg HomeRentals) and 'version' - although those could probably be determined by looking at the bytecode of the ListingRegistry. Perhaps the TrustedRegistries contract could have another mapping: sha3(bytecode) => { version, type }.

**Comment by wanderingstan** [comment]
I'm not seeing the need for a meta-registry. IMO it introduces unneeded complexity.

Category segmentation (e.g. HomeRentals vs RideShare) is already accounted for in the Listing Schema and shouldn't be duplicated. 

Versioning could be done with the Listing contract interface. 

My proposal to keep things simple (sort of off the cuff here):
- Break out the logic of `ListingsRegistry` into an upgradable Library. Here will live the code for creating Listings, creating them with whatever is our latest version of our `Listing` contract. 
- Keep the storage of `ListingsRegistry` as "dumb" as possible -- its just a bag of contract addresses. (Array/Map) (but can only be added to via the library's `create()` method.)
- Define a minimum interface for `Listing` contracts, which includes a method `version()`, which  can be used to know what version of a listing contract you're dealing with, so you know what methods/ABI to use.

**Comment by tyleryasaka** [comment]
I agree with @wanderingstan, at least for where we are right now. Depending on how we build things to support multiple vendors, I could *possibly* imagine a scenario where it would be helpful to have a meta-registry; that's a separate discussion. But I think a single registry is definitely all we need at this stage.

I also like the general structure @wanderingstan proposed for separating data and logic. 💯

**Comment by DanielVF** [comment]
While I'm 94.5% percent sure that we'll eventually need to support multiple listing contracts with different logic, for now we do have only one contract type that is only by us. Thus, a listing registry contract with upgradable listing creation, and constant time contract verification will handle us as we are right now.

Rather than using an upgradable library for creation, I think the better route is to turn it around have the logic live in the public Listing Registry and have a dumb, persistent storage contract that does the long term data holding. This way we can change the Listings Registry's methods in the future - for example to add new arguments to creating a new contract. We just spin up a new Listing Registry and transfer the storage contract's ownership to it.

**Comment by DanielVF** [comment]
Our current contract architecture handles all of this. YAY. 

Closing this.
