### ISSUE TITLE
Broken Add to Calendar link on Readme 

### ISSUE THREAD

**Issue by gaboesquivel** [OriginProtocol/origin-js#165]
The Add to Calendar link on the readme file is broken

**Comment by joshfraser** [comment]
How about now? The link is right, but the permissions may be off.

**Comment by gaboesquivel** [comment]
yeah, it seems you need to make the calendar public and also publish the event
https://support.google.com/calendar/answer/41207?hl=en

**Comment by micahalcorn** [comment]
[This has been removed](https://github.com/OriginProtocol/origin-js/commit/6537a9766311a402797b34bc9427a2ece01fdef1#diff-04c6e90faac2675aa89e2176d2eec7d8).
