### ISSUE TITLE
IPFS always goes to local instead of gateway

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-js#173]
Still investigating, but the demo dapp on master, when installed using the current 0.5.9 npm version of origin-js, always seems to look for a local IPFS daemon. 

I attempted to change the preferences in demo-dapp that are passed to the `Origin()` constructor, but they are not being respected.

I added the gateway as fallbacks in `origin.js` in `demo-dapp` like this:

```
import Origin from 'origin'

let config = {}

config.ipfsDomain = process.env.IPFS_DOMAIN ? process.env.IPFS_DOMAIN : "gateway.originprotocol.com"
config.ipfsApiPort = process.env.IPFS_API_PORT ? process.env.IPFS_API_PORT : "443"
config.ipfsGatewayPort = process.env.IPFS_GATEWAY_PORT ? process.env.IPFS_GATEWAY_PORT : "443"
config.ipfsGatewayProtocol = process.env.IPFS_GATEWAY_PROTOCOL ? process.env.IPFS_GATEWAY_PROTOCOL : "https"

const origin = new Origin(config)
window.web3 = origin.contractService.web3

export default origin
```

marking this as "high priority" since it means that our `master` readme is lying when it says that you can have dapp running with just an `npm install` and `npm run start`.

**Comment by wanderingstan** [comment]
Just tried again with version 0.5.10 ([checklist here](https://github.com/OriginProtocol/origin-js/issues/176)) and this issue still persists. 

How are defaults handled?

**Comment by nick** [comment]
Hmm is this still an issue for you? Master branch demo-dapp with origin 0.5.10 (non npm-linked) works fine for me pointing to the production IPFS gateway. Do you have a `.env` file overriding the defaults?

**Comment by wanderingstan** [comment]
Fixed in the last release! Closing.
