### ISSUE TITLE
Update contract to allow ownership retention during migration

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#195]
@ambertch will need an update to the contracts so that creators of listings will not lose ownership after the migration script (via #148) is run.

**Comment by wanderingstan** [comment]
Quick commit to add this method: https://github.com/OriginProtocol/origin-js/commit/ce839c54094980152cf70375e77fe98bb9fdbeda

@ambertch I think this should be what you need?

**Comment by ambertch** [comment]
@wanderingstan thanks! I pushed an update to the migration branch:

- listings are now migrated using `ListingsRegistry.createOnBehalf()` 
- updated ListingsRegistry ABI (for the migration script)
- includes the lister field when checking checksums
