### ISSUE TITLE
Update readme with info on heroku deploy

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-js#203]
On discord, @msklyarov asked about deploying origin-js changes on heroku. 

This was my rough answer. Should be cleaned up and put in readme or docs.

> As you discovered, a heroku instance can't get the full dev environment that we have around origin-js. (Our npm run start command launches a local blockchain and local IPFS daemon) So if you've made changes to origin-js that you want to show the world on  a heroku deploy there are a few steps:
> 1) Change package.json on your demo-dapp repo to point to your origin-js on github. That is, change this line to point to your repo#branch:
> https://github.com/OriginProtocol/demo-dapp/blob/develop/package.json#L16
> 2) If you've changed the contracts (*.sol) files you'll need to deploy those to ropsten/rinkeby. Ask me if you need help with that. 
> ...actually, this should be in our documentation!
>

**Comment by msklyarov** [comment]
@wanderingstan 
When I'm trying to add npm as a GitHub branch I'm getting an error:

$ cd demo-dapp
$ npm uninstall origin -S
$ npm i https://github.com/OriginProtocol/origin-js -S
$ npm start

> origin-demo-dapp@0.3.0 start /home/maxim/WebstormProjects/Jolyy/demo-dapp
> if [ "$NODE_ENV" = "production" ]; then npm run serve; else npm run dev; fi


> origin-demo-dapp@0.3.0 dev /home/maxim/WebstormProjects/Jolyy/demo-dapp
> webpack-dev-server --open

Failed to load ./.env.
clean-webpack-plugin: /home/maxim/WebstormProjects/Jolyy/demo-dapp/build has been removed.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1505:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! origin-demo-dapp@0.3.0 dev: `webpack-dev-server --open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the origin-demo-dapp@0.3.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maxim/.npm/_logs/2018-05-23T10_16_55_351Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! origin-demo-dapp@0.3.0 start: `if [ "$NODE_ENV" = "production" ]; then npm run serve; else npm run dev; fi`
npm ERR! Exit status 1

or:
$ npm start

> origin-demo-dapp@0.3.0 start /home/maxim/WebstormProjects/Jolyy/demo-dapp
> if [ "$NODE_ENV" = "production" ]; then npm run serve; else npm run dev; fi


> origin-demo-dapp@0.3.0 dev /home/maxim/WebstormProjects/Jolyy/demo-dapp
> webpack-dev-server --open

clean-webpack-plugin: /home/maxim/WebstormProjects/Jolyy/demo-dapp/build has been removed.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1505:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! origin-demo-dapp@0.3.0 dev: `webpack-dev-server --open`
npm ERR! Exit status 1

with .env.dev renamed to .env

===============================================
$ cat ./2018-05-23T10_25_43_232Z-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle origin-demo-dapp@0.3.0~prestart: origin-demo-dapp@0.3.0
6 info lifecycle origin-demo-dapp@0.3.0~start: origin-demo-dapp@0.3.0
7 verbose lifecycle origin-demo-dapp@0.3.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle origin-demo-dapp@0.3.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/maxim/WebstormProjects/Jolyy/demo-dapp/node_modules/.bin:/home/maxim/bin:/home/maxim/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle origin-demo-dapp@0.3.0~start: CWD: /home/maxim/WebstormProjects/Jolyy/demo-dapp
10 silly lifecycle origin-demo-dapp@0.3.0~start: Args: [ '-c',
10 silly lifecycle   'if [ "$NODE_ENV" = "production" ]; then npm run serve; else npm run dev; fi' ]
11 silly lifecycle origin-demo-dapp@0.3.0~start: Returned: code: 1  signal: null
12 info lifecycle origin-demo-dapp@0.3.0~start: Failed to exec start script
13 verbose stack Error: origin-demo-dapp@0.3.0 start: `if [ "$NODE_ENV" = "production" ]; then npm run serve; else npm run dev; fi`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid origin-demo-dapp@0.3.0
15 verbose cwd /home/maxim/WebstormProjects/Jolyy/demo-dapp
16 verbose Linux 4.13.0-39-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error origin-demo-dapp@0.3.0 start: `if [ "$NODE_ENV" = "production" ]; then npm run serve; else npm run dev; fi`
22 error Exit status 1
23 error Failed at the origin-demo-dapp@0.3.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Could you please advise what I need to change?

**Comment by wanderingstan** [comment]
Have you tried just editing the package.json directly? That's what we usually do.

**Comment by msklyarov** [comment]
It starts but can't find any contracts.
I replaced string in package.json:
"origin": "git+https://github.com/OriginProtocol/origin-js.git"
rm node_modules
npm i
npm start

**Comment by msklyarov** [comment]
@wanderingstan the situation is similar to previous one:
![image](https://user-images.githubusercontent.com/16777084/40428996-38d82086-5eaa-11e8-9821-f51856bfb29d.png)

**Comment by wanderingstan** [comment]
Note: This issue would be helped by debug output: https://github.com/OriginProtocol/origin-js/issues/217

Also: @msklyarov - Remind me again what it is that you're trying to accomplish?

> It starts but can't find any contracts.
> I replaced string in package.json:
> "origin": "git+https://github.com/OriginProtocol/origin-js.git"

Ah, of course! This is referring to our github repo, but *the repo does not contract addresses committed in it*. The contracts have to be deployed first (usually to ropsten or rinkeby) and this will generate a `/contracts/build/` directory with json files containing info for each contract. 

_These files are not committed to git._

That's the heart of the problem. Thanks for bringing that to our attention. 

I think the only ways to make this work are: 
1. (Preferred) manually set the contract addresses with the `CONTRACT_ADDRESSES` environment variable. (This can be set in heroku)
2. Commit `/contracts/build` directory to your repo. Either self-generated or copied from e.g. the published npm package. (Not 100% sure this would work.)

The `CONTRACT_ADDRESSES` var is not well documented. You can get the flavor of it here: 

https://github.com/OriginProtocol/origin-js/blob/49fe587c5fe1380015ec35422edb2fed857312f6/test/contract-service.test.js#L102-L107

So looks like we'd need to assemble a json blob containing all of our deployed contract addresses. I don't think there's a way to get this aside from manual work right now. :(

`CONTRACT_ADDRESSES` 
```
{ 
  userRegistryContract: { 4: { address:"0x1234567890123456789012345678901234567890" } }, 
  listingsRegistryContract: { 4: { address:"0x9876543210987654321098765432109876543210" } } ,
  <more contracts here>
} 
```

@nick Is there any easy way to assemble all our contract addresses? Maybe outputting this json blob would be a good function for issue #217 ?

**Comment by nick** [comment]
So far I've been assembling them manually from your contract deployment output when we do a release.

Perhaps we could have an origin.info() method which outputs things like version, contract addresses, bridge server address, IPFS address, etc which can be used in the browser console. We could even print it to the console when starting the demo-dapp with `npm start`

**Comment by maxim-lexical** [comment]
@wanderingstan 
package.json:
"origin": "git+https://github.com/OriginProtocol/origin-js.git"

$ export CONTRACT_ADDRESS="{ userRegistryContract: { 4: { address:"0x1234567890123456789012345678901234567890" } },  listingsRegistryContract: { 4: { address:"0x9876543210987654321098765432109876543210" } } }"

$ npm i
$ npm start

Same issue on localhost:
The Origin Contract was not found on this network.
You may need to change networks, or deploy the contract.

**Comment by msklyarov** [comment]
@wanderingstan
package.json:
"origin": "git+https://github.com/OriginProtocol/origin-js.git"

$ export CONTRACT_ADDRESS="{ userRegistryContract: { 4: { address:"0x1234567890123456789012345678901234567890" } }, listingsRegistryContract: { 4: { address:"0x9876543210987654321098765432109876543210" } } }"

$ npm i
$ npm start

Same issue on localhost:
The Origin Contract was not found on this network.
You may need to change networks, or deploy the contract.

But it works with heroku without setting of config var.

**Comment by wanderingstan** [comment]
@msklyarov 
> But it works with heroku without setting of config var.
I thought getting this working on heroku was the goal? I'm surprised it would work there without setting the `CONTRACT_ADDRESS` env var. Are you sure your heroku deploy isn't using the npm package?

I'm also not sure what contract it "tests" to determine if Origin contracts are there. I do know that there are a lot more than just those two contracts (`userRegistryContract` and `listingsRegistryContract`, however.) So that could be what's causing the problem locally.

Again, what is it that you're trying to accomplish? Or are you just testing the use of a github branch instead of the npm module?

**Comment by msklyarov** [comment]
>Or are you just testing the use of a github branch instead of the npm module?
Right. If it'll work for unmodified branches then I'll move to the next step.

**Comment by azizsallam** [comment]
Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)

**Comment by wanderingstan** [comment]
@azizsallam can you give more context on your error? 

Otherwise I'm thinking we close this issue.

**Comment by tomlinton** [comment]
@azizsallam that error will occur if you have something else running on port 3000 (the port used by origin-dapp, I'm guessing you received that error when starting origin-dapp rather than origin-js).

**Comment by wanderingstan** [comment]
Going to call this one closed, as there hasn't been activity in a while.
