### ISSUE TITLE
copy zeppellin contracts over to contracts/ instead of importing node_modules/openzeppelin-solidity

### ISSUE THREAD

**Issue by gaboesquivel** [OriginProtocol/origin-js#208]
I recommend stop using node_modules/openzeppelin-solidity and instead copy the necessary contract files over to contracts/openzeppelin for 2 reasons.

- More control of the code the actually being imported, although in theory semver should guarantee we always the same version
- Testing Coverage. In order to get the testing coverage report properly reporting the correct amount solidity code that is being tested I had to make this change in the past.  This is related to #197

**Comment by tyleryasaka** [comment]
I disagree. I think it's premature to worry about having that level of control of this code. The entire point of using the zeppelin contracts is that it gives us one less thing to worry about while we build out early iterations.

**Comment by gaboesquivel** [comment]
I actually agree with you. This was probably more a comment to #197, since it was mainly because of the code coverage reporter not playing well with imported open zeppelin contracts. We had to copy paste the zeppelin contracts along with the tests for those contract in order to reach full coverage in the report.

**Comment by wanderingstan** [comment]
I agree too. Closing this one out.
