### ISSUE TITLE
Fractional usage engineering design document

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#218]
For the 🏗 sprint, let's aim for having a fully-baked engineering design document for fractional usage.

- [x] Outline "finalized" engineering decisions
- [x] Design all-purpose contract
- [x] Spec out API

Related: #146 & https://github.com/OriginProtocol/demo-dapp/issues/242

**Comment by wanderingstan** [comment]
Additional discussion here: https://github.com/OriginProtocol/origin-js/issues/146

**Comment by micahalcorn** [comment]
Done [here](https://docs.google.com/document/d/131XzwVNGlZ6itINS_Gy0o0dYzRtN_5NQXbcqXZuL2vk) 📝
