### ISSUE TITLE
Rename github repos to include "origin"

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-js#220]
Our current primary repos are named:
- bridge-server
- origin-js
- mobile-app
- demo-dapp
- company-website
- docs
- identity-playground

When a user clones or forks one of our repos, they will have a directory of this name on their computer (if cloned) or repo appear on their github profile (for forks).

Thus divorced from the context of our github account, our repo names become generic and unidentifiable. In a folder full of dozens of projects, "mobile-app" won't mean much of anything. Likewise for "company-website". 

Other projects follow the convention of prefixing generic-sounding repos with their name. See truffle for example:
![image](https://user-images.githubusercontent.com/673455/40754860-b34d4ce0-6438-11e8-9203-b46a11f12c68.png)

On the other side, can you spot the origin repos in this folder? :)
![image](https://user-images.githubusercontent.com/673455/40755133-401a9cc6-643a-11e8-93ee-a5392d73de4d.png)

And here is how our repos appear on a github profile. Again, out of context names like "company-website" or "mobile-app" mean very little. 
![image](https://user-images.githubusercontent.com/673455/40755339-50783ef6-643b-11e8-8ea0-f86858afc5b3.png)

People are, of course, free to rename their local folders if we get tired of typing "origin" all the time. 

I would propose:
- origin-bridge-server
- origin-js
- origin-mobile-app
- origin-demo-dapp
- origin-company-website
- origin-docs
- identity-playground (maybe leave this as its not specific to origin?)

**Comment by DanielVF** [comment]
(I've got an `origin` folder, and everything happily lives there.)

**Comment by wanderingstan** [comment]
> I solved this by using a parent Origin folder that contains all my Origin repos. Curious what other people are doing.

My concern is not for our comfort, but for open source contributors who are _not_ part of the Origin team. They are the ones who will have a random "Repos" folders where they clone all the things they're playing around with. When they come back in a month, will they even remember what "company-website" is?  They are the ones whose friends will look at their github profile and ask, "What is this 'mobile-app' thing you're working on? Not very descriptive!"

For us who live and breath these repos, it's easy enough to rename them to shorter names for our `origin` folders if we like.

**Comment by nick** [comment]
I agree with @wanderingstan and @tyleryasaka that forking 'demo-dapp' to nick/demo-dapp then cloning to a local 'demo-dapp' directory is not as descriptive as origin-demo-dapp when looking at forks and local project dirs. Keeping everything in a parent 'origin' dir works if you are a well organized person, which I'm not ;-)

Perhaps we could even take the opportunity to simplify some repo names:

- origin-bridge
- origin-js
- origin-mobile
- origin-dapp
- origin-website
- origin-docs

**Comment by joshfraser** [comment]
Okay, I'm convinced. I like @nick's proposal of using shorter names though.

**Comment by wanderingstan** [comment]
I also like @nick's shorter names. Super sleek and concise.

**Comment by wanderingstan** [comment]
@joshfraser , I believe as repo owner you're going to have to be the one do this one.

**Comment by joshfraser** [comment]
Done
