### ISSUE TITLE
Docker: Sync origin-js source between local filesystem and container

### ISSUE THREAD

**Issue by tyleryasaka** [OriginProtocol/origin-js#228]
I'm thinking we'll want to use [Docker volumes](https://docs.docker.com/storage/volumes/) to achieve this. I [did something similar a while back, in the demo dapp. It doesn't work any more, [here is an example](https://github.com/OriginProtocol/demo-dapp/blob/master/docker-compose.yml) using docker-compose.

See https://github.com/OriginProtocol/origin-js/pull/227#issuecomment-395558722 for why we need this.

Or, we may not want docker to be running the origin-js dev environment at all: https://github.com/OriginProtocol/origin-js/issues/230 .

**Comment by ahaidery** [comment]
I can help out with this one if possible?

**Comment by franckc** [comment]
@ahaidery Thanks for offering to help ! :) @tomlinton has actually a setup of docker-compose that uses volume - check out [this branch](https://github.com/OriginProtocol/origin-box/tree/compose) as well as this [discussion](ttps://github.com/OriginProtocol/origin-js/issues/229). We are in the process of testing out this setup - would you want to give it a try and give any feedback ?

**Comment by tyleryasaka** [comment]
Yeah, this issue should have been closed already. We solved this problem in origin-box. Thanks @ahaidery .
