### ISSUE TITLE
Pagination: Listings

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#264]
**Simple**: Once https://github.com/OriginProtocol/origin-bridge/issues/99 is completed, the API should accept pagination-related parameters and pass them through to the bridge server.

~**Not So Simple**: Once https://github.com/OriginProtocol/origin-js/issues/263 is completed, the all method should handle the pagination-related parameters directly and manage pagination of listings retrieved directly from the blockchain.~
Let's skip this. 👍

**Comment by micahalcorn** [comment]
This should wait until Tyler and Nick are done with the big contract and API refactor.

**Comment by sparrowDom** [comment]
This has already been done by someone
