### ISSUE TITLE
Bare-bones prototype for upgradeable token contract

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#277]
Build a bare-bones, prototype contract for experimenting with token mechanics.

**Comment by matthewliu** [comment]
Let's be very explicit with how we name this. Is this issue in reference to the base wrapper contract that at Cuong is working on? If so, let's name it something more descriptive and precise.

**Comment by cuongdo** [comment]
The prototypes were created as part of #284, and the initial token implementation merged with #345
