### ISSUE TITLE
Arbitration: Centralized Contract Prototype

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#278]
Integrate a [centralized arbitrator](https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/CentralizedArbitrator.sol) contract as a prototype for adding dispute resolution to our purchase contracts.

**Comment by wanderingstan** [comment]
After discussions with @nick , we're not going to use ERC 792 for V1. It's simpler+cheaper to just put an offer into "dispute" mode rather than calling a method on an arbitrator contract. We can always add it back in later via a proxy contract.
