### ISSUE TITLE
Admin: Listing Curation Methods

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#283]
There should be non-blockchain methods on the Listings resource for updating indexed listings with "hidden" or "featured" flags. The getter method[s] should also accept parameters for retrieving only listings that meet the relevant criteria.

Related: https://github.com/OriginProtocol/origin-bridge/issues/117

**Comment by tyleryasaka** [comment]
So just to make sure I follow - this is going to be an integration between origin-js and origin-bridge, yeah? We'd store these flags somewhere in origin-bridge?

**Comment by franckc** [comment]
As opposed to doing any computation in origin-js, this will likely involve origin-js passing some options (ex: exclude/include-hidden-listings or exclude/include-featured-listtings) when calling the bridge server to either get listings or search listings.

**Comment by micahalcorn** [comment]
No longer relevant ☑️
