### ISSUE TITLE
Implement a Node.js EventListener daemon

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-js#290]
As part of the indexing system, we want to build an "EventListener" server written in Node.js that listens to blockchain events from Origin smart contract and pushes those to the bridge server. The "EventListener" core logic for interacting with the blockchain and IPFS should be built as methods in the origin-js library.

Details are documented in the [indexing design doc](https://docs.google.com/document/d/1v6N--Ncyea12irHysE8QafmjnCRy01YKm7Fqtxq2rNc/edit#heading=h.e7xf3tll2cs3).

**Comment by tyleryasaka** [comment]
I'm glad to help with this as well.

**Comment by franckc** [comment]
I was chatting with @sparrowDom and we agreed it would be nice to have the following capabilities for the EventListener:
1. Ability to pass options on the command line argument or via a config file. This way, while deploying the same codebase, we could configure different instances of the EventListener to behave differently.
2. An option to have the EventListener wait N confirmations (N being configurable) before calling the webhook with an event. This would be particularly useful for mobile notifications since we don't want to send those to the end-user's mobile until we are pretty sure the transaction won't get rolled back.
3. start_block and end_block options - that would when we want to re-index the data for a range of blocks.

**Comment by micahalcorn** [comment]
@franckc do we consider this done with https://github.com/OriginProtocol/origin-js/pull/367?

**Comment by franckc** [comment]
Yes. It is done. Closing this puppy.

**Comment by franckc** [comment]
Filed #407 to specifically track the work on block confirmation, which is not implemented yet.
