### ISSUE TITLE
Initial token implementation

### ISSUE THREAD

**Issue by cuongdo** [OriginProtocol/origin-js#295]
The initial token implementation will include:

- Basic ERC-20 functionality
- Mint (create new) tokens
- Burn tokens
- Pause & unpause transfer of tokens

Additionally, it will be upgradeable as required by #284.

This will not include wiring up the token to any user flows.

**Comment by micahalcorn** [comment]
@cuongdo we should close this?

**Comment by cuongdo** [comment]
Not yet, but I will with a PR I want to get out in the next day

**Comment by cuongdo** [comment]
Just the contract changes are in #345

The rest of the changes will be done as a series of small(ish) PRs to prevent overload on reviewers.

**Comment by cuongdo** [comment]
Resolved by #345
