### ISSUE TITLE
Tool for distributing tokens to investors

### ISSUE THREAD

**Issue by cuongdo** [OriginProtocol/origin-js#296]
Once tokens are generated, we need to:
- Distribute tokens to all investors 
- Enforce lockups
- Protect investor privacy

This would likely consist of two parts: 
- A new smart contract to hold tokens during their lockup period
- A command-line JS tool that would distribute tokens to investors after the lockup period expires. It would take as input a file that @joshfraser and/or @matthewliu would create and maintain.

**Comment by filiplazovic** [comment]
Can i work on this issue?

**Comment by cuongdo** [comment]
@filiplazovic: I should've updated this issue earlier, but I'm already pretty far along on this. Please take a look at the [other Solidity issues](https://github.com/OriginProtocol/origin-js/labels/solidity) and see if there's anything else that interests you.

**Comment by filiplazovic** [comment]
@cuongdo Perhaps https://github.com/OriginProtocol/origin-js/issues/585?

**Comment by micahalcorn** [comment]
Closing per @franckc 💰
