### ISSUE TITLE
Commissions: UI components

### ISSUE THREAD

**Issue by cuongdo** [OriginProtocol/origin-js#311]
As proposed by @nick and described in [his document](https://docs.google.com/document/d/1jhkl5uYYNUyLcQvLmswYzugFufLivXpbGCNQkKXBzlI/edit).

These are the general requirements:
* For v1, we are not going to allow buyers and sellers to negotiate the commission rate
* DApps will set a suggested or default rate, and the sellers may change that (similar to how Ethereum gas works)
* Commissions will be earned by the DApp the services the final transaction.
* To qualify for commissions, DApp partners will stake Origin token (see #286)

This task tracks the UI component work.

**Comment by micahalcorn** [comment]
**Related**
https://github.com/OriginProtocol/origin-dapp/issues/424
(will list more as they get added)

**Comment by micahalcorn** [comment]
Closing in favor of the following, more granular issues:

https://github.com/OriginProtocol/origin-dapp/issues/424
https://github.com/OriginProtocol/origin-dapp/issues/432
https://github.com/OriginProtocol/origin-dapp/issues/434
https://github.com/OriginProtocol/origin-dapp/issues/435
https://github.com/OriginProtocol/origin-dapp/issues/436
https://github.com/OriginProtocol/origin-dapp/issues/437
