### ISSUE TITLE
Messaging: Conversation Syncing

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#338]
In some circumstances, it is possible for only one of the two users to get the shared room key stored in its local database. I'm not sure why this happens.

Potentially related: some users don't seem to be finding the other users' keys in Orbit.

**Comment by tomlinton** [comment]
Is this something we've seen lately? If anyone has any possible ideas for reproducing please throw them out there. :grin:

**Comment by micahalcorn** [comment]
I'm going to assume that our recent issues are attributable to the Go vs JS situation and move this to the backlog for now.

**Comment by tomlinton** [comment]
@micahalcorn this was raised pre `go-ipfs` (that has only been in use for a week or so). I was thinking `go-ipfs` might have solved it so I asked about it above, but now that we are reverting back to `js-ipfs` it is probably still important.

**Comment by micahalcorn** [comment]
No longer relevant with the recent centralization efforts ☑️
