### ISSUE TITLE
Token contract integration

### ISSUE THREAD

**Issue by cuongdo** [OriginProtocol/origin-js#346]
Now that the basic Origin token contract has landed with #345, we need to integrate it into our code. These are the required steps:

- [ ] Fork / vendor OpenZeppelin token code
- [x] Replacing `contracts/Token.sol` with `contracts/token/OriginToken.sol`
- [x] Add Truffle migration for deployment
- [x] Integration into marketplace contract
- [x] Integrate OpenZeppelin token tests
- [x] Create our own tests for anything OpenZeppelin's tests don't cover (e.g. burn permissions)
- [ ] Contract migration infrastructure
  - We need to write and test this before we actually need it
- [x] Contract whitelisting (if we decide that this needs to be part of main contract)
- [ ] Launch as part of test release (depends on #374)

This issue doesn't cover any work specific to the mainnet launch of the token.

cc @nick @DanielVF

**Comment by cuongdo** [comment]
cc @micahalcorn

**Comment by micahalcorn** [comment]
Related https://github.com/OriginProtocol/origin-js/issues/314 & https://github.com/OriginProtocol/origin-js/issues/313 ☑️

**Comment by cuongdo** [comment]
This is sufficiently done for me to close. The remaining tasks now have their own issues: #313 and #422
