### ISSUE TITLE
Test Data Generation Script

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#360]
In preparation for scale, we should have script that generates thousands of test listings.

**Comment by micahalcorn** [comment]
@DanielVF feel free offer your thoughts on this.

**Comment by DanielVF** [comment]
Probably a simple node script that loads origin.js as a library and then goes to town making data.

**Comment by ambertch** [comment]
The listings generation doesn't necessarily need to be complex either,
since any difference in a piece of content creates a different content
hash. If things like upload sizes or geolocation/geosearch have to be
tested, then specific types of test data will be required.

**Comment by DanielVF** [comment]
Yay! We've got a basic version of this going in #448
