### ISSUE TITLE
Faucet for Origin token on Testnet

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-js#374]
In order to be able to test the DApp on Testnet, we'll need a way for test wallets to get credited with some OGN tokens.

A simple UI similar to https://faucet.ropsten.be/ will be exposed (perhaps hosted under https://faucet.originprotocol.com ?). The user enters her wallet address and will get credited with a fixed amount of tokens. There won't be any rate limiting.

Additionally, for ease of testing on local development environment, it would be nice to have a simple JS script that can be run manually and credits OGN token to a wallet address passed as argument on the command line.

**Comment by franckc** [comment]
CC @cuongdo @nick @DanielVF as FYI since this is related to the token project.

**Comment by micahalcorn** [comment]
Done 😁
