### ISSUE TITLE
Support security deposit in marketplace contracts

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-js#375]
Marketplace contracts need to support the concept of "security deposit".

1. At listing creation time, seller enters an optional security deposit amount which is separate from the item amount.
2. Both security deposit and item amount must be in the same currency. In V1 the only currency supported is ETH. 
3. Both item and security deposit amounts are "recommendation" from the seller and are not enforced at the contract layer. A buyer could make an offer that does not match those amounts. But in V1, we will enforce at the origin-js layer that the offer made by the buyer matches both the item amount and the security deposit amount recommended by the seller.
4. When the offer is accepted by the seller, the total of item amount + security deposit amount is withdrawn from buyer account and put in escrow.
5. When the sale gets finalized, the seller gets credited with item amount and the buyer gets her security deposit back.
6. In case of a dispute, the distribution amounts of both the item amount and security deposit amount can be changed by either a) the buyer and seller agreeing or b) a 3rd party arbitrator the dispute got escalated to. For example a dispute resolution can result in returning X% of the item amount and/or Y% of the security deposit amount to the buyer.

**Comment by franckc** [comment]
@matthewliu @wanderingstan Can you check I got those requirements right ?
Also CC @cuongdo @nick @DanielVF as FYI.

**Comment by matthewliu** [comment]
@franckc requirements LGTM. The only additional detail is the timeout periods. @micahalcorn

**Comment by nick** [comment]
LGTM too. I’m currently working on adding non-binary arbitration to the
marketplace contract so can add this in too as it should be a fairly minor
change. I’ll just add one more parameter to makeOffer so that the refund
can be initialized to something other than 0. The refund can then be used
to return the security deposit.

**Comment by franckc** [comment]
@nick - If you are already updating that area of the marketplace code then let's not overlap. I'll let you add the security deposit support. Could you make me the reviewer though ? I want to catch up on contracts code... Thanks !

**Comment by nick** [comment]
While implementing this I realized that it's probably better that the buyer is not able to 'pre-populate' the security deposit as they could theoretically finalize the offer and receive back their whole security deposit back. Taking the home share example:

- Seller creates listing specifying 100 DAI/nt + 200 DAI security deposit
- Buyer makes offer for 400 DAI (2 nights) with an auto refund of 200 DAI
- Buyer breaks a lamp while staying at the property
- Buyer checks out and 'finalizes' offer - receiving their 200 DAI deposit back (as it was pre-populated)
- Seller checks house and finds stuff broken, but security deposit has already been returned

Instead, their should be an extra step before finalization where the seller sets the refund:

- Seller creates listing specifying 100 DAI/nt + 200 DAI security deposit
- Buyer makes offer for 400 DAI (2 nights)
- Buyer breaks a lamp while staying at the property
- Buyer could finalize early, but then they'd lose all their security deposit
- Seller checks house and finds broken lamp, sets refund to 150 DAI instead of full 200
- Buyer can either finalize the offer and get 150 DAI back... or dispute the transaction and go to arbitration

Thoughts? Are there any other times when it's be useful for the buyer to pre-populate their refund on-chain? I can't think of one myself...

**Comment by franckc** [comment]
I can't think neither of a normal case where it would be useful for the buyer to be able to pre-populate the security deposit refund... 

The only caveat might be in case of a dispute that hasn't been escalated yet to an arbitrator and where seller/buyer are messaging each other to mutually agree on a resolution. Would we want both buyer and seller to be able to set the refund ? I think it would be ok if, after agreeing via messaging on the refund amount, then only the seller can set it in the contract.

Also, I'm still fuzzy on the requirements around timeout/finalization. Would be good to get a bit more clarity on this to make sure there is no edge-cases we haven't considered that would allow either buyer or seller to defraud the other party.

@matthewliu Could you comment on the above ?

**Comment by matthewliu** [comment]
@franckc @nick i agree with what both of you have said above around the security deposits. i can't think of a situation where the buyer should be able to get his deposit back before the seller has a look.

@micahalcorn is going to add us explicitly on the issue for timeouts franck. let's have that discussion there.

**Comment by wanderingstan** [comment]
@franckc writes:
> The only caveat might be in case of a dispute that hasn't been escalated yet to an arbitrator and where seller/buyer are messaging each other to mutually agree on a resolution. Would we want both buyer and seller to be able to set the refund ? I think it would be ok if, after agreeing via messaging on the refund amount, then only the seller can set it in the contract.

Ideally we'd want buyer seller agreement to be able to happen in either order. E.g. these should be equivalent:
1. Buyer requests 0.5 ETH refund, Seller agrees.
2. Seller offers 0.5 ETH refund, Buyer agrees. 

Given the above, I'm not sure how we'd handle case (2). The seller would then need to take another action to "make it so"? 

Or is there some fancy solidity coding where the seller would pre-sign a transaction that the buyer could then run? 

Then there's the whole question of who pays the gas... I think we need a wider discussion of how/when/by-whom these contract-altering transactions take place.

**Comment by matthewliu** [comment]
@nick @franckc I just want to understand if offer and refund explicitly break out the listing price vs. the security deposit. I understand that the math works out the same, but to me a refund is different from releasing the security deposit. In more complex scenarios that are yet TBD, I could see there being the possibility of treating these two sums of money very differently.

**Comment by franckc** [comment]
@matthewliu Here is what we have currently:
  - The contract only keeps track of a total amount (which is the sum of listing price+security deposit). The refund amount is variable between 0 and total amount. Under a normal scenario, when the transaction finalizes the refund amount is set to the amount of the security deposit (e.g. buyer gets back her deposit). But in case of a dispute, the refund amount could vary. In extreme cases a refund of 0 means buyer loses everything (listing price + deposit), while a refund of total amount means buyers gets back everything.
   - In the JSON for the offer, we do keep track of the listing price and the security deposit amount. So these separate amounts can be presented in the DApp UI and also can be used by the origin-js logic (for example for implementing the refund amount logic).

Hope this clarifies. Happy to chat tomorrow if you have further questions.

**Comment by wanderingstan** [comment]
Not to complicate things, but we should also support the possibility of numbers being changed on either "side of the ledger": 
E.g. the buyer may ask to stay an extra night, and then add more funds. 
E.g. the seller may concede that the place wasn't cleaned, and reduce the price (moving it into the refund/security-deposit)

**Comment by matthewliu** [comment]
@franckc got it. As long as origin-js and the DApp layer are sufficient, I'm cool with the contract being "simplified". Are there any edge cases we might be missing? Just want to make sure. I guess we are assuming (as we are with many other decisions at the moment), that people will not be interacting with the contracts directly.

@wanderingstan this does make things more complicated in all parts of the stack (DApp, origin.js, contracts). I'm perfectly fine not including this in v1 if you are.

**Comment by franckc** [comment]
@matthewliu Yes, this assumes people do not interact with contracts directly but thru DApp/Origin-js. Which I think is ok as a start. BTW, to clarify, while the contract support for security deposit will be in V1 contracts, we haven't really discussed the UI flows. What is the priority of adding security deposit to the UI for V1 ?

@wanderingstan: I think the current contract should be able to support the 2 scenarios you mentioned (though as Matt mentioned that would be extra DApp/origin-js work so I'd agree we should probably not worry about implementing this initially):
  - Asking for an extra night stay: buyer talks to seller to ask if extra night available (and price). if yes, buyer withdraws current offer, then make a new offer with value = original night price + extra night price + security deposit. There is a method "makeOffer" that allows to withdraw + make new offer atomically in the marketplace contracts.
  - Seller reducing price: buyer contacts seller before finalization, asks for a reduced price. Seller agrees and calls "updateRefund" to increase refund beyond security deposit. When finalization happens, buyer effectively gets security deposit + extra which is equivalent to a reduced price.

**Comment by nick** [comment]
@franckc withdraw + make new offer only works if the seller has not already accepted the original offer. To solve that, I think it could be worthwhile to allow the buyer to add funds to an already accepted offer with a new 'addFunds' method. Since it's only adding (and not removing) funds, I think it should be a fairly simple and safe method to add.

**Comment by franckc** [comment]
@nick Ah yes, good point re withdraw+make new offer. Agreed that adding a "addFunds" method would work - I can take a stab at adding this.

**Comment by micahalcorn** [comment]
📣 As decided in a meeting today with Matt, we will mock up the UI for deposits but not implement it in the DApp until we are ready to include fractional usage.

**Comment by wanderingstan** [comment]
@micahalcorn Good to know. This then settles self-arbitration as well, as it relies on having the "refund" value—so this will also have to wait until after V1.

**Comment by nick** [comment]
`addFunds` has been added as part of #401 - the buyer can now add extra funds to an accepted offer.

**Comment by franckc** [comment]
Awesome. Thanks @nick !

Closing this issue since we now have everything needed for supporting security deposis at contract level for our initial release.

There is some work remaining at origin-js and dapp UI but that should be tracked via different github issues.

**Comment by franckc** [comment]
Closing.
