### ISSUE TITLE
Marketplace compatibility with  future token contracts

### ISSUE THREAD

**Issue by cuongdo** [OriginProtocol/origin-js#376]
Origin.js should get the token contract address through ENS, to allow even older Origin.js versions to access the current token contract.

**Comment by nick** [comment]
Right now the token address is baked into the Marketplace contract and there is no way to update it. Perhaps we can add an updateToken method, then use the marketplace contract as the source of the active token address?

**Comment by cuongdo** [comment]
@nick I like that idea. Would the new `updateToken` function be protected by `onlyOwner` from OpenZeppelin's `Ownable` contract?

**Comment by nick** [comment]
Yep, that'd work. I'm not sure the marketplace needs all the features of Ownable though - we could just have a variable `owner` that is set to msg.sender in the constructor and checked in updateToken, perhaps?
