### ISSUE TITLE
Enable Sellers To Decline Offers

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#392]
Per this week's [sprint meeting](https://docs.google.com/document/d/1DvRWYhrr0UXdvhyZIpEd3WEU-1pQk2Frj1l-mQS8B4M), a listing will be considered "sold out" at the DApp level if there is one valid, outstanding offer (whether accepted or awaiting acceptance). And buyers will not be able to dictate their own offer terms. So in order to enable sellers to free up listings for other buyers, they will need to have the ability to decline offers.

**Comment by nick** [comment]
This has been added as part of #401
