### ISSUE TITLE
origin.js API for getting OGN balance

### ISSUE THREAD

**Issue by cuongdo** [OriginProtocol/origin-js#405]
We need an API for retrieving the user's token balance, which will be displayed in several places, such as the following:

![image](https://user-images.githubusercontent.com/1564582/45050912-7add5d00-b050-11e8-88e0-f53a3a24d1b2.png)

**Comment by micahalcorn** [comment]
Thanks @cuongdo, I was just about to ping you about this. Any idea how we will convert it to USD in the short-term?
