### ISSUE TITLE
Commit ABI files after each release

### ISSUE THREAD

**Issue by tyleryasaka** [OriginProtocol/origin-js#434]
We have decided, for the short term, to follow the process described by @wanderingstan in this comment: https://github.com/OriginProtocol/origin-js/pull/368#issuecomment-416367087

1. So after each release, we will store the resulting ABI files in a directory something like: `origin-js/contracts/releases/X.X.X/build/`.
2. Then in our origin-js build script, we will copy over the ABIs from the latest release build, if a local build does not yet exist.

**Comment by DanielVF** [comment]
We might want to commit some abi files from the previous release, so we can start using this feature.

**Comment by wanderingstan** [comment]
@DanielVF good idea. I'm just about to board my flight but will try to do this. Feel free to commit the ones from the .zip file currently there. Sadly those may be the only abi files we have. I previously saved the contract addresses in the [release notes](https://github.com/OriginProtocol/origin-js/releases), but that was all... :(

**Comment by franckc** [comment]
I will start working on this on Friday.

**Comment by franckc** [comment]
Implemented in #459. Closing
