### ISSUE TITLE
Arbitration: Minimal Arbitrator workflow

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-js#453]
Origin will be the sole arbitrator for our first version. 

An employee with the "blessed" eth account needs to be able to: 

- [ ] 1. See list of offers that are in dispute
- [x] 2. See the listing details for a disputed offer (for the time the offer was accepted, in case it has since changed)
- [ ] 3. Read the evidence (ie messaging between buyer and seller) for a disputed offer
- [x] 4. Engage in conversation with buyer and seller
- [ ] 5. Make a ruling (ie call the `executeRuling()` method of marketplace contract.

**Comment by wanderingstan** [comment]
@micahalcorn you mentioned that you have early versions of 3. (reading shared conversations) and a react component for an arbitrator UI.  What branches are these in?

**Comment by micahalcorn** [comment]
Yeah, I haven't made PRs yet, but the branches are pushed. I will PR them if by some miracle I'm done with the UI before @jordajm is done with the API. I may need a little bit of guidance from you, @wanderingstan, if the ruling is more involved than a button in the seller's favor and a button in the buyer's favor. 🔘

**Comment by micahalcorn** [comment]
@wanderingstan I've updated this list with boxes checked. ☑️ I'll work on 3, investigate 1, and hold off on 5.

**Comment by micahalcorn** [comment]
Actually, I'm going to move these to their own issues.
