### ISSUE TITLE
Optimise build script and allow builds when NODE_ENV is set to production

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-js#491]
It is not possible to do a production build without installing all of the devDependencies from the `package.json`. This is very slow, and since we have to build `origin-js` for other parts of the stack it makes updating deployments very slow also.

The build script [here](https://github.com/OriginProtocol/origin-js/blob/master/scripts/build.js) imports a lot of things we don't need for a production build (`ganache`, `ipfs`, `chalk`, `node-watch` look like examples of this, there might be more). If we could avoid installing all of this stuff every time we do a production build the build time would be cut way down.

The `build.js` script at the moment is more like a mini dev environment rather than a build script. I think in the long term we should move some of the services it creates (`ganache`, `ipfs`) to `origin-box`. In the short term, perhaps a separate script to just do builds of `origin-js`?

**Comment by tomlinton** [comment]
This has become more important because we can't build `origin-js` with NODE_ENV=production for use in the staging deployment because of all the dev dependencies that get imported. We ran into an issue that we only discovered in the production deployment/published npm package because we didn't run the same setup in staging. Also I'm sure @franckc would appreciate any speed gains in deploying the DApp. :grin:

Might chuck a `p1` on this. You need any help with it @tyleryasaka?

**Comment by tyleryasaka** [comment]
I'm prioritizing this now. Shouldn't be difficult.

**Comment by tomlinton** [comment]
Closed as no longer relevant due to dapp2.
