### ISSUE TITLE
Arbitration: Resolved UI

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#495]
We need to handle the components' state when arbitration is completed (both for the participants and the arbitrator.

**Comment by wanderingstan** [comment]
...well, ideally we'd show some note indicating if it was solved by arbitration. In the future, we're also distinguish between resolved via mediated arbitration vs self-settlment of participants. 

Something like how AirBnB does here:
https://drive.google.com/drive/folders/1TD7nsX04W-2CAmceFG6Qgaj5WiUauYtC

**Comment by micahalcorn** [comment]
Resolved by https://github.com/OriginProtocol/origin-dapp/pull/634 ✅
