### ISSUE TITLE
Determine issuers list

### ISSUE THREAD

**Issue by tyleryasaka** [OriginProtocol/origin-js#500]
We need a list of public keys for issuers to associate with our Origin identity on each network (mainnet, rinkeby, etc.)

**Comment by franckc** [comment]
Code with keys: https://github.com/OriginProtocol/origin-js/blob/master/contracts/migrations/5_create_sample_issuers.js#L4

**Comment by wanderingstan** [comment]
Also: I think we should rename the vars, as right now it uses `ISSUER_PROD` for any network that isn't `development`, ie rinkeby. Perhaps `ISSUER_STAGING` ? 

https://github.com/OriginProtocol/origin-js/blob/master/contracts/migrations/5_create_sample_issuers.js#L45

**Comment by wanderingstan** [comment]
I'm gonna just go with these addresses for now, though I don't know the source or who has the corresponding private keys. @tyleryasaka is that you?

**Comment by franckc** [comment]
Marking this issue as blocking for the Mainnet launch.

@tyleryasaka can you confirm what value we should use for STAGING and PROD ?

**Comment by wanderingstan** [comment]
@tyleryasaka writes in discord:

> I'm not at a computer right now. But really I don't have the keys... We have something in envkey but I'm not sure that's what we want to actually use. I think Josh is the person to ask

**Comment by franckc** [comment]
I verified that ISSUER_PROD is the public address for the ATTESTATION_SIGNING_KEY private key stored in production ENVKEY. I think we are all good so closing this ticket.
