### ISSUE TITLE
🐃 Origin.js does not pass along the listing arbitrator, offer arbitrator, or offer affiliate

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-js#537]
Origin.js does not set the listing arbitrator, offer arbitrator, or offer affiliate in the models. This is a problem since knowing who the offer arbitrator is, is absolutely required to safely accept a offer. As it is, there's no way for the DAPP to be able to display this to the user.

**Comment by cuongdo** [comment]
Because `listings` and `offers` are public variables in `V00_Marketplace`, Solidity auto-generates public accessor methods for them. So, given a listing's index, shouldn't it be possible to access the required info?

**Comment by DanielVF** [comment]
Yes, I did miss that. Updated issue to be origin.js only.

**Comment by DanielVF** [comment]
Fixed for now in https://github.com/OriginProtocol/origin-js/pull/549
