### ISSUE TITLE
Smart Contract Audits

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#540]
Just leaving a note here for any discussion relevant to the auditing of our smart contracts.

@nick mentioned that the identity contracts are very much in alpha status and may not be ready for auditing.

**To-Do**s
- [ ] add disclaimer comment(s) to the identity contract(s) @franckc

**Comment by franckc** [comment]
CC @tyleryasaka since he is very involved in everything related to ERC 725

**Comment by tyleryasaka** [comment]
Yeah I'm researching identity heavily right now and have a lot of thoughts and ideas that I'm exploring. Agreed they will likely change a good bit in the near future.

**Comment by micahalcorn** [comment]
[Done](https://drive.google.com/a/originprotocol.com/file/d/19oVP05ygCwgJzwTweOvIhdtPbhVCd2UJ/view?usp=sharing) ✅
