### ISSUE TITLE
Invalid Offer Developer Experience

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#558]
As mentioned [here](https://github.com/OriginProtocol/origin-js/pull/549#issuecomment-424766738) and [here](https://github.com/OriginProtocol/origin-dapp/issues/554#issuecomment-424843451), it may not be appropriate to [throw errors](https://github.com/OriginProtocol/origin-js/pull/549/commits/7ddc933a52f40cea49a5c8bcdb942f2704e3bf11) when invalid offers are retrieved. If a method is called, which internally retrieves all offers matching a certain criteria, these errors will surface and prevent the returning of the expected value. This is a bad developer experience because the caller didn't explicitly ask for the invalid thing and the request itself was valid. This can also lead to side effects that are bad for end users.

I don't know if it's best to just silently swallow the invalid offers, log errors, or what.

cc @franckc @DanielVF @tyleryasaka

**Comment by micahalcorn** [comment]
@DanielVF but if I call [`getNotifications`](https://github.com/OriginProtocol/origin-js/blob/master/src/resources/marketplace.js#L358-L383) and someone has injected an invalid listing that matches my filters, I will never get them, right?

**Comment by tyleryasaka** [comment]
I'll fix this shortly
