### ISSUE TITLE
Messaging: Missing Room Participant

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#559]
An edge case appeared recently in the staging environment where a room was created but one of the participants was missing the other. This likely resulted from the remote server failing to persist the data.

**Comment by crazybuster** [comment]
we could have the clients periodically update the counterparty time stamps in their conv-init dbs, but it might be overkill.

**Comment by micahalcorn** [comment]
This should no longer be relevant thanks to the recent centralization efforts. ☑️
