### ISSUE TITLE
Discovery server: price range query failure

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-js#595]
On the DApp on Mainnet, if I query for "Mountain" with a price range of [$222 - $231], the Discovery server returns an error. This is its response: https://gist.github.com/franckc/91a09a03040f61cbb51a728aaad4481d

So it looks like the query created for this price range may be invalid ?

Note that given price range the query should return zero listings (the only listing that matches "Mountain" has a price of 1ETH = $219). It's probably part of the problem because if I use a price range that includes the listing there is no error....

Pull Request solving problem: https://github.com/OriginProtocol/origin-dapp/pull/713

**Comment by sparrowDom** [comment]
Fixed via: https://github.com/OriginProtocol/origin-dapp/pull/713
