### ISSUE TITLE
Repo structure breaks npm builds with two packages

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-js#67]
We currently have 2 npm packages in this repo: one for the [contracts](https://github.com/OriginProtocol/platform/blob/develop/packages/contracts/package.json) and one for [origin.js. ](https://github.com/OriginProtocol/platform/blob/develop/packages/origin.js/package.json).

This caused my `npm build` in origin.js to fail, as I hadn't yet done an `npm install` for the contracts. I suspect this would be a nightmare for new developers, and seems to over complicate things. 

@aiham , I recall you saying it was strange to have dependencies outside the directory of the `package.json`. What would you think would be a better layout? 

Our original idea was to mimic the layout of [RequestNetwork](https://github.com/RequestNetwork/requestNetwork/tree/master/packages), who do indeed have two packages. They seem to solve it by having the `.js` package [include the smartcontract package as a dependency](https://github.com/RequestNetwork/requestNetwork/blob/master/packages/requestNetwork.js/package.json#L40). This could work, but feels strange to have the contracts as an npm package.

@DanielVF : any thoughts on this? 
@Gzing : You were following requestNetwork; have you heard any discussion on their side about this?

**Comment by aiham** [comment]
@wanderingstan 

Yes it's a requirement to build `contracts` first. That's exactly right, why I mentioned it strange for `origin` to reference something from a parent directory. Looks like RequestNetwork is using [lerna](https://lernajs.io/) to maintain and publish multiple packages at once. Their SmartContracts package is set to private so it does not get published, but its [exportArtifacts.js](https://github.com/RequestNetwork/requestNetwork/blob/master/packages/requestNetworkSmartContracts/exportArtifacts.js) file is used to generate everything inside a `exports/` directory which is somehow (likely manually) copied over to the artifacts package folder, which is then published to npm, and like you said, it's a dependency of the main requestNetwork.js package.

This is a bit fiddly but we could replicate it if you'd like. What's the advantage of having everything in a single directory with a single package.json and just have different build steps for the contracts and the JS. WDYT?

**Comment by aiham** [comment]
Yeah I don't think there's any point in splitting it into multiple modules right now, its seems like premature optimisation, especially since we're not even publishing the contracts package. There's not much reason to start publishing it either since it doesn't have multiple dependants at this stage.

**Comment by Gzing** [comment]
RequestNetwork and 0x(https://github.com/0xProject/0x-monorepo) follow this monorepo styled packages using Lerna (https://github.com/lerna/lerna) to build and symlink the packages.
![screenshot from 2018-03-30 13-42-03](https://user-images.githubusercontent.com/2235865/38153198-42e7f0a6-3420-11e8-8289-7f51ac126b84.png)

But it does add developer overhead and complicate things. I think we can go ahead with @aiham 's recommendation and not split the packages into different modules.

**Comment by wanderingstan** [comment]
There was more discussion around this in discord, and especially around how we share the contract json ABI to python (for bridge server code). 

The consensus there was that we can just copy-paste the ABI's for now. (git-submodules were another possibility, but this was rejected as introducing a 2nd form of package control.)

So I think the plan is:
1. Remove npm package around our contract code. (I.e. remove `package.json` etc from in `contracts` dir [here](https://github.com/OriginProtocol/platform/tree/develop/packages/contracts))
2. Move contract `.sol` files to be within `origin.js` directory, per npm standards.  
3. (Presumably) flatten directory structure, moving `origin.js` to be the top directory in this repo
4. (Suggested) rename this repo to be `origin.js`, as that's closer to what it is. 

@joshfraser - I know we've discussed renaming this repo before, as per (4) above. Do you agree with this game plan? 

We should also then think about long term plan for contract ABI's, as "copy-paste" can't work forever. I haven't looked extensively, but other projects seem to put them in separate repo's or npm modules. More exotic options could be to have repos grab the source code from etherscan (and compile ABI), or for us to "publish" the ABI or source code to IPFS. We should open a new issue to discuss this.

**Comment by tyleryasaka** [comment]
We've simplified the npm structure - one npm package at the root level. Closing.
