### ISSUE TITLE
Latest release of origin.js should be available via originprotocol.com

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-js#75]
EDIT: **Finished! URL is: https://code.originprotocol.com/origin-js/origin-v0.5.10.js** 
 
Now that we have a plain javascript `origin.js` (not the npm version) we should make it available from our website, which ideally just points to a IPFS blob.

So a site should be able to do something like:
```
<script src="https://www.originprotocol.com/code/v0.0.2/origin.js"></script>
```

This could in turn be a redirect to an IPFS blob:
https://gateway.originprotocol.com/ipfs/QmU85WSZMtdMaf7kuyTZpztSKQuVdVY7cXpMCeKa3y1vW5
Such an approach has the advantage that clients don't have to trust our website not to change the code. The IPFS hash will only and always point to an exact version. 

This also would make for a cool demo in that one could start using origin.js in the raw browser console, loading it with only this code:
```
document.head.innerHTML += '<script src="https://www.originprotocol.com/code/v0.0.2/origin.js"></script>';
```

Currently this code lives only in our releases here:
https://github.com/OriginProtocol/platform/releases

@joshfraser What do you think?

**Comment by joshfraser** [comment]
Yes, yes, yes!

We can setup `code.originprotocol.com` to make this easier to serve from a CDN if we want. I like the idea of serving it from IPFS as well, although performance could be an issue. We should probably put the version number in the filename (`origin-0.0.2.js`) instead of the path to avoid naming collisions when we roll out other libraries in the future like origin-ui.js. 

Request a specific version:

`<script src="https://code.originprotocol.com/origin-0.0.2.js"></script>`

Return the latest version:

`<script src="https://code.originprotocol.com/origin.js"></script>`

**Comment by wanderingstan** [comment]
@joshfraser - You're instinct was correct. We **can** just serve from github releases. 

This line worked in a simple .html page:
```
<script src="https://github.com/OriginProtocol/platform/releases/download/v0.2.60/origin.js"></script>
```

So we can fulfill this issue with just a redirect from `originprotocol.com` 

How about this? 
`https://www.originprotocol.com/code/origin-vX.X.X.js` 
redirects to:
`https://github.com/OriginProtocol/platform/releases/download/vX.X.X/origin.js`

**Comment by wanderingstan** [comment]
We agreed @joshfraser would do this, redirecting to e.g. https://unpkg.com/@originprotocol/origin@0.2.60

**Comment by wanderingstan** [comment]
With our change of npm package, new redirect pattern is:
```
code.originprotocol.com/origin@0.5.8
```
redirects to
```
https://unpkg.com/origin@0.5.8/dist/origin.js
```
(Unless we also wanted to make available the `npm` package version, which is at `https://unpkg.com/origin@0.5.8/dist/index.js`)

**Comment by wanderingstan** [comment]
@joshfraser Any progress on this? IIRC, this needs to be done at the DNS level.

I could do it with a redirect in flask if we were okay something more like `www.originprotocol.com/code/xxxxx`

**Comment by wanderingstan** [comment]
@joshfraser writes on discord:

> Josh Fraser - Last Friday at 8:23 PM
> @wanderingstan https://code.originprotocol.com/origin-js/origin-v0.5.10.js
> I'm using Flask to fetch the file directly from Github for now. don't think it matters with our current traffic levels. will need to revisit this in a few months, but it's good enough for today.

Interesting tidbit: I was going to suggest we use unpkg instead of serving from github, but looks like they somehow only serve an uncompressed verion. (`mode: 'production'` vs mode: `'development'` in `webpack.config.js`??) 
https://unpkg.com/origin@0.5.10/dist/index.js

Considering this done and closed.
