### ISSUE TITLE
Add auto testing of origin.js

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-js#92]
Presumably using codeship, though of course we could have discussion around other options since we haven't started using it. 

@Gzing - I've added you to our team on codeship, let me know if you need anything else on that front. 

- Is it worth creating similar issues for website, demo-dapp? 
- `identity-playground` does have tests defined. Shall we create an issue there as well?

**Comment by micahalcorn** [comment]
@tyleryasaka this is done via #114, yeah?

**Comment by tyleryasaka** [comment]
@micahalcorn DONE ✅ 😃
